### ISSUE TITLE
咨询key

### ISSUE THREAD

**Issue by lovinglover** [DA1YAYUAN/JD-comments-sentiment-analysis#1]
请问这个key是什么，产品的productID吗，我打开京东产品的url都是这样的 https://item.jd.com/100008348542.html ，这个key要怎么获取呢，我使用F12检查，也没找到这个productID

**Comment by DA1YAYUAN** [comment]
在"Please enter the address:"后，输入完整的京东商品URL就可以爬取了。开始key值是完整URL，之后传入spider_comment中时为URL中的productID。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DA1YAYUAN/JD-comments-sentiment-analysis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月20日(星期二) 下午2:10
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[DA1YAYUAN/JD-comments-sentiment-analysis] 咨询key (#1)





 
请问这个key是什么，产品的productID吗，我打开京东产品的url都是这样的 https://item.jd.com/100008348542.html ，这个key要怎么获取呢，我使用F12检查，也没找到这个productID

**Comment by DA1YAYUAN** [comment]
**第60、61行**
`key = input("Please enter the address:")`      key: 'https://item.jd.com/71810342874.html'
`key = re.sub("\D","",key)`      key: '71810342874.'

**Comment by lovinglover** [comment]
感谢，我debug也看到了，然后这样拼接出来的URL，可以直至使用浏览器打开，但是用request无法打开，我怀疑是header不完整，就把我浏览器里的header内容全写进去了，但还是打不开
https://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv4646&productId=100008348542&score=0&sortType=5&page=0&pageSize=10&isShadowSku=0&fold=1


    r_json_str = r.text[26:-2]
    UnboundLocalError: local variable 'r' referenced before assignment
这个是报错信息，我断点看了，request.get没成功，正常来讲，header里写入cookie不应该就可以了么

**Comment by lovinglover** [comment]
我找到问题了，urllib3版本问题，我降到 1.25.11版本就可以
